[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
etherscan_api_key= "${ETHERSCAN_API_KEY}"

# See more config options https://github.com/gakonst/foundry/tree/master/config